# Generated by Django 4.2 on 2023-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210411_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
